package com.camelcasing.image.gif;

import java.util.Arrays;

/**
 * Basically a wapper Class for an int[] with <code>HashCode</code> and <code>Equals</code> overridden 
 * to allow arrays to be added to a <code>HashMap</code> and exploit the <code>Contains</code> method. 
 * For use in the {@link com.camelcasing.image.gif.LZWCompressor LZWCompressor} class
 * 
 * @author camelCasing
 * @version 0.2
 * @since 0.2
 */
public class InputColour{

		private int[] colour;
	
	/**
	 * @param colour generated by {@link com.camelcasing.image.gif.GIFUtils GIFUtils} to help the {@link com.camelcasing.image.gif.LZWCompressor LZWCompressor}
	 */
	public InputColour(int[] colour){
		this.colour = colour;
	}

	public int[] getColour(){
		return colour;
	}

	public int getSize(){
		return colour.length;
	}
	
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + Arrays.hashCode(colour);
		return result;
	}

	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		InputColour other = (InputColour) obj;
		if (!Arrays.equals(colour, other.colour))
			return false;
		return true;
	}
}
